### PR TITLE
added chezy drive

### PR DESCRIPTION
**Pull request by ajbt200128**

### CODE REVIEW

**Review by mayerm94 — CHANGES_REQUESTED** [review]
You should rename the 'plagarism.....' classes to be descriptive about what they do. Also, consider putting a link to the source that you copied it from in the drive class, that will pay tribute to the people who actually put work into the code, and will help link back to see if they have made any changes to it up-stream

**Comment by jmadigan** [comment]
> You should rename the 'plagarism.....' classes to be descriptive about what they do. Also, consider putting a link to the source that you copied it from in the drive class, that will pay tribute to the people who actually put work into the code, and will help link back to see if they have made any changes to it up-stream

Looks like this issue has been completed

**Comment by ajbt200128** [comment]
No it's closed smh not completed. Didn't want to change the name nor give credit

**Comment by jmadigan** [comment]
> No it's closed smh not completed. Didn't want to change the name nor give credit

Good luck revesting your shares.

**Comment by mayerm94** [comment]
> > You should rename the 'plagarism.....' classes to be descriptive about what they do. Also, consider putting a link to the source that you copied it from in the drive class, that will pay tribute to the people who actually put work into the code, and will help link back to see if they have made any changes to it up-stream
> 
> Looks like this issue has been completed

Wow, I can't believe the integrity I tried to instill in you guys years ago.... Did it work?

**Comment by ajbt200128** [comment]
It worked for me 😆 OSS or die

**Pull request closed without merging**
